zookeeper:
  image: samsara/zookeeper
  ports:
    - "2181:2181"
    - "15001:15000"
  environment:
    ZK_SERVER_ID: 1
  volumes:
    - /tmp/docker/zk1/logs:/logs
    - /tmp/docker/zk1/data:/data

kafka1:
  image: samsara/kafka
  container_name: kafka1
  ports:
    - "9092:9092"
    - "15002:15000"
  links:
    - zookeeper
  environment:
    KAFKA_OFFSETS_STORAGE: kafka
  volumes:
    - /tmp/docker/kafka1/logs:/logs
    - /tmp/docker/kafka1/data:/data

kibana:
  image: kibana:4.3.0
  ports:
    - "8000:8000"
    - "5601:5601"
  links:
    - elasticsearch
  environment:
    ELASTICSEARCH_URL: http://elasticsearch:9200

elasticsearch:
  image: elasticsearch:2.1.0
  ports:
    - "9200:9200"
    - "9300:9300"
    - "15005:15001"
  volumes:
    - "/esdata"
